name: Release

on:
  push:
    tags: 
      - 'v*'

permissions:
  contents: write
  
jobs:
  build-binary:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@master
        with:
          name: action-ask-bing
          path: target/release/action-ask-bing
  release-binary:
    name: Release
    needs: build-binary
    runs-on: ubuntu-latest
    steps:
      - name: download productions
        uses: actions/download-artifact@master
        with:
          name: action-ask-bing
          path: .
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: action-ask-bing

