name: Ask

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write cookies to file     
      env:
        COOKIES: ${{ secrets.COOKIES }}
      run: echo $COOKIES > cookies.json

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        cache: 'pip'
        python-version: "3.10"
    
    - run: pip install -r requirements.txt

    - name: Execute app.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        python app.py

